# Generated by Django 4.2.6 on 2023-10-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='ErrandTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state_within', models.CharField(blank=True, max_length=100, null=True)),
                ('pick_up_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('pick_up_long', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('drop_off_address', models.CharField(max_length=255)),
                ('drop_off_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('drop_off_long', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('recipient_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('grocery_list', models.JSONField(blank=True, null=True)),
                ('grocery_estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('describe_errand', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('ARRIVED', 'ARRIVED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=20)),
                ('user_cancelled', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='errands_as_agent', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='errands_as_customer', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, to='api.file')),
                ('rejected_agents', models.ManyToManyField(blank=True, null=True, related_name='errands_rejected', to=settings.AUTH_USER_MODEL)),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subtype')),
            ],
        ),
    ]
