# Generated by Django 4.2.6 on 2023-10-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='how_long',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
