# Generated by Django 4.1.3 on 2024-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='agent_rating',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=100, null=True),
        ),
    ]
