# Generated by Django 4.2.6 on 2023-10-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_errandtask_how_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='drop_off_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
