# Generated by Django 4.1.3 on 2024-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_errandtask_agent_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='agent_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
