# Generated by Django 4.2.6 on 2023-11-01 00:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_errandtask_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='sender_contac',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
