# Generated by Django 4.1.3 on 2024-01-24 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_errandtask_agent_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('p', 'Pending'), ('c', 'Complete'), ('f', 'Failed')], default='p', max_length=100)),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('errands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.errandtask')),
            ],
        ),
    ]
