# Generated by Django 4.1.3 on 2024-01-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errandtask',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('ARRIVED', 'ARRIVED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PICKED_UP', 'PICKED_UP'), ('CANCELLED', 'CANCELLED')], default='REQUESTED', max_length=20),
        ),
    ]
