# Generated by Django 4.2.6 on 2023-11-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_errandtask_sender_contac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errandtask',
            old_name='sender_contac',
            new_name='sender_contact',
        ),
    ]
