# Generated by Django 4.2.6 on 2023-11-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_sender_contac_errandtask_sender_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errands_as_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='errandtask',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errands_as_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
