# Generated by Django 4.2.6 on 2023-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehiclemetric_errandtask_distance_in_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
