# Generated by Django 4.2.6 on 2023-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_errandtask_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='distance_in_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
