# Generated by Django 4.1.3 on 2023-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_errandtask_distance_in_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='estimated_drop_off_time',
            field=models.DurationField(blank=True, default='00:55:00', null=True),
        ),
        migrations.AddField(
            model_name='errandtask',
            name='estimated_pick_up_time',
            field=models.DurationField(blank=True, default='00:35:20', null=True),
        ),
    ]
