# Generated by Django 4.1.3 on 2023-12-06 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='estimated_drop_off_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3300), null=True),
        ),
        migrations.AlterField(
            model_name='errandtask',
            name='estimated_pick_up_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=2120), null=True),
        ),
    ]
