# Generated by Django 4.1.3 on 2023-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_errandtask_estimated_drop_off_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='estimated_drop_off_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='errandtask',
            name='estimated_pick_up_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
