# Generated by Django 4.1.3 on 2023-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_errandtask_category_alter_errandtask_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('ARRIVED', 'ARRIVED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('PICKED_UP', 'PICKED_UP')], default='REQUESTED', max_length=20),
        ),
    ]
