# Generated by Django 4.1.3 on 2023-12-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_errandtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='errandtask',
            name='grocery_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
