# Generated by Django 4.1.3 on 2023-12-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_message_options_alter_errandtask_grocery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errandtask',
            name='how_long',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
