# Generated by Django 4.1.3 on 2023-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_errandtask_how_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errandtask',
            name='how_long',
        ),
        migrations.AddField(
            model_name='errandtask',
            name='time_cap',
            field=models.CharField(blank=True, choices=[('HOURS', 'HOURS'), ('DAYS', 'DAYS'), ('MONTHS', 'MONTHS')], max_length=100, null=True),
        ),
    ]
