# Generated by Django 4.1.3 on 2023-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_errandtask_how_long_errandtask_time_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='errandtask',
            name='how_long',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
