# Generated by Django 4.2.6 on 2023-10-09 17:27

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='id_file',
            field=models.ImageField(default=1, upload_to='uploads/agents-documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_type', to='accounts.idtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferece_as_agent', to='accounts.preferences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='services',
            field=models.ManyToManyField(related_name='services_as_agent', to='accounts.services'),
        ),
    ]
