# Generated by Django 4.2.6 on 2023-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_idtype_preferences_services_agent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='arrival_speed',
            field=models.PositiveIntegerField(default=1, help_text='How fast can you drive in km/h?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='bank_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='beneficiary_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='delivery_speed',
            field=models.PositiveIntegerField(default=1, help_text='How fast can you drive in km/h?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='pay_per_hour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/agents-photos'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_long',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_file',
            field=models.FileField(upload_to='uploads/agents-documents'),
        ),
    ]
