# Generated by Django 4.2.6 on 2023-10-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agent_account_number_agent_arrival_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='beneficiary_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
