# Generated by Django 4.2.6 on 2023-10-28 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_agent_beneficiary_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='beneficiary_number',
            new_name='beneficiary_name',
        ),
    ]
