# Generated by Django 4.2.6 on 2023-10-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_beneficiary_number_agent_beneficiary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='arrival_speed',
            field=models.PositiveIntegerField(blank=True, help_text='How fast can you drive in km/h?', null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='delivery_speed',
            field=models.PositiveIntegerField(blank=True, help_text='How fast can you drive in km/h?', null=True),
        ),
    ]
