# Generated by Django 4.2.6 on 2023-10-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_agent_arrival_speed_alter_agent_delivery_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='pay_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
