# Generated by Django 4.2.6 on 2023-11-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_agent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_completed',
            field=models.BooleanField(default=False),
        ),
    ]
