# Generated by Django 4.2.6 on 2023-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_account_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='arrival_speed',
            field=models.IntegerField(blank=True, help_text='How fast can you drive in km/h?', null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='delivery_speed',
            field=models.IntegerField(blank=True, help_text='How fast can you drive in km/h?', null=True),
        ),
    ]
