# Generated by Django 4.2.6 on 2023-11-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_distancemetric_vehiclemeric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistanceMetric',
        ),
        migrations.DeleteModel(
            name='VehicleMeric',
        ),
    ]
