# Generated by Django 4.1.3 on 2023-12-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='photo',
        ),
    ]
