# Generated by Django 4.1.3 on 2023-12-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_agent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
