# Generated by Django 4.1.3 on 2024-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
