# Generated by Django 4.1.3 on 2024-01-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_agent_average_rating_alter_agent_id_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_file',
            field=models.FileField(default=1, upload_to='uploads/agents-documents'),
            preserve_default=False,
        ),
    ]
