# Generated by Django 4.1.3 on 2024-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_agent_id_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_file',
            field=models.URLField(),
        ),
    ]
